/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eas.aoc

import kotlin.test.Test
import kotlin.test.assertEquals

class Day1Test {
    val test_file = "src/test/resources/d1-test-data"
    val actual_file = "src/test/resources/d1data"

    @Test
    fun testDay1Two() {
        val test_answer = 514579
        val ans = findMatchingSumTwo(test_file)
        assertEquals(ans, test_answer)

    }

    @Test
    fun testDay1Three() {
        val test_ans = 241861950
        val ans = findMatchingSumThree(test_file)
        assertEquals(ans, test_ans)

    }

    @Test()
    fun testRunDay1Two() {
        val ans = findMatchingSumTwo(actual_file)
        print("Actual day 1 (two) answer $ans\n")
    }

    @Test()
    fun testRunDay1Three() {
        val ans = findMatchingSumThree(actual_file)
        print("Actual day 1 (three) answer $ans\n")
    }
}
