/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eas.aoc

import kotlin.test.Test
import kotlin.test.assertEquals

class Day3Test {
    val test_file = "src/test/resources/day3-test-data"
    val actual_file = "src/test/resources/day3data"

    @Test
    fun testDay2Pt1() {
        val test_answer = 7
        val ans = findValidTreeCount(test_file)
        assertEquals(ans, test_answer)

    }

    @Test
    fun testDay2ActualPt1() {
        val ans = findValidTreeCount(actual_file)
        print("Number of trees discovered: $ans\n")
    }

    @Test
    fun testDay2ActualPt2() {
        val file = actual_file
        val ans = 7812180000
        val oneOne = findValidTreeCount(file, 1, 1)
        val threeOne = findValidTreeCount(file, 3, 1)
        val fiveOne = findValidTreeCount(file, 5, 1)
        val sevenOne = findValidTreeCount(file, 7, 1)
        val oneTwo = findValidTreeCount(file, 1, 2)
        val actualAnswer = oneOne.toLong() * threeOne * fiveOne * sevenOne * oneTwo
        assertEquals(ans, actualAnswer)
        print("Number of trees discovered pt 2: $actualAnswer\n")
    }


}
