/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eas.aoc

import kotlin.test.Test
import kotlin.test.assertEquals

class Day4Test {
    val test_file = "src/test/resources/day4-test-data"
    val actual_file = "src/test/resources/day4data"

    @Test
    fun testDay4Pt1() {
        val file = test_file
        val test_answer = 2
        val ans = findValidPassportCountPt1(file)
        assertEquals(ans, test_answer)

    }

    @Test
    fun testDay4ActualPt1() {
        val file = actual_file
        val test_answer = 2
        val ans = findValidPassportCountPt1(file)
        print("Day 4 Pt 1 valid passports: $ans \n")

    }

    @Test
    fun testDay4ActualPt2() {
        val file = actual_file
        val test_answer = 2
        val ans = findValidPassportCountPt2(file)
        print("Day 4 Pt 2 valid passports: $ans \n")

    }


}
